name: L10n Validate

on:
  pull_request:
    paths:
      - 'lib/l10n/**'
      - 'l10n.yaml'
      - '.weblate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Generate localizations
        run: flutter gen-l10n
      - name: Analyze
        run: flutter analyze
